### ISSUE TITLE
convertion from `float` to `size_t` in `aeolus::dsp::Chiff::Chiff()`

### ISSUE THREAD

**Issue by KottV** [Archie3d/aeolus_plugin#1]
Hi!

g++ complains when compiling:

```
/home/kv/src/audio/aeolus_plugin/Source/aeolus/dsp/chiff.cpp:32:7: error: narrowing conversion of ‘4.41e+4f’ from ‘float’ to ‘size_t’ {aka ‘long unsigned int’} [-Wnarrowing]
   32 |     , _pipeResonator{SAMPLE_RATE}
```

**Comment by Archie3d** [comment]
Hi, thanks for the report.
What is your build environment (I've only built on Windows so far)?
Please retry from the latest master, I've pushed the update (667a2b4de51020ae4a42bcb5b86d284207f37cd4).

**Comment by KottV** [comment]
Yeah, it's g++ 11.1.1 on Linux (openSUSE TW) and this commit has fixed that
Thank You!
