### ISSUE TITLE
Registers with names in red

### ISSUE THREAD

**Issue by Victor-Ch** [Archie3d/aeolus_plugin#16]
I'm not very good on organs. Could you explain what does name in red mean as to registers?

**Comment by Grillzombie** [comment]
In my opinion, red is for reeds.

**Comment by Victor-Ch** [comment]
Ok. Thank you.

**Comment by Grillzombie** [comment]
There are two families of pipes in an organ:
Principal etc. are lip pipes, trumpet etc. are reed pipes

**Comment by Archie3d** [comment]
Yes, this is correct, red labels are to indicate the reed stops. This is a common practice, but it is not universal. For example if I read from George Ashdown Audsley's "The Art of Organ-Building":
> _The names of the stops and their pitches should in all cases be boldly rendered, either in block letters or plain Gothic text. When the latter is adopted, the initial or capital letters should be in red and the small letters and numbers  in black. This treatment has a very pleasing effect, and is to be especially recommended for the Chamber Organs, in which every external feature should be rich, refined, and artistic._

This suggests that colouring scheme is more of an aesthetics touch, and the reed stops highlighting brings a bit of a functional information into this.
