### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by dxmann** [Archie3d/aeolus_plugin#17]
Is it possible to build this plugin on linux?
Many thanks!

**Comment by Archie3d** [comment]
Hi, yes, the plugin builds on Linux as VST3 and standalone executable. It should be possible to build LV2 as well, but I've never bothered.
Here, I've uploaded the build from GitHub action (ubuntu/debian) for v0.1.13: https://github.com/Archie3d/aeolus_plugin/releases/download/v0.1.13/Aeolus-standalone-vst3-linux-0.1.13.zip

**Comment by dxmann** [comment]
I think I will build it on voidlinux, I have to check how: lv2 or vst3.

**Comment by Archie3d** [comment]
You may check the build script for the dependencies to install: https://github.com/Archie3d/aeolus_plugin/blob/master/.github/workflows/build.yml
I am not familiar with VoidLinux, so you're on your own here, good luck! 😀

**Comment by dxmann** [comment]
I'm trying to build on voidlinux with an automatic tool: xbps-src;
I have an error con cmake execution:
```
CMake Error at CMakeLists.txt:31 (add_subdirectory):
  The source directory

    /builddir/aeolus_plugin-0.1.13/JUCE

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:55 (juce_add_plugin):
  Unknown CMake command "juce_add_plugin".


-- Configuring incomplete, errors occurred!
```

What can I do? I'm not expert about cmake

**Comment by dxmann** [comment]
ok OpenSUSE Tumbleweed works fine!

**Comment by Archie3d** [comment]
Right, you need to make sure to clone the submodules. I am glad it worked for you after all.
