### ISSUE TITLE
VST plugin for win-64 (v0.1.13)

### ISSUE THREAD

**Issue by Victor-Ch** [Archie3d/aeolus_plugin#19]
Could you build version 0.1.13 as VST plugin for win-64 (like "Aeolus-vst-win64-0.1.12.zip")?
That would be great.

**Comment by ppelikan** [comment]
There is an VST3 plugin for win-64 in the releases section: [Aeolus-vst3-win64-0.1.13](https://github.com/Archie3d/aeolus_plugin/releases/download/v0.1.13/Aeolus-vst3-win64-0.1.13.zip)

**Comment by Archie3d** [comment]
[Here you go](https://github.com/Archie3d/aeolus_plugin/releases/download/v0.1.13/Aeolus-vst-win64-0.1.13.zip).
What is your host that is still requires VST2 plugins?

**Comment by Victor-Ch** [comment]
Thank you very much!

I use Aeolus with Avid Sibelius 2022 - it does not support any VST3 plugins, unfortunately.
