### ISSUE TITLE
Occasionally reverb and output volume raise up to max

### ISSUE THREAD

**Issue by sangiye0** [Archie3d/aeolus_plugin#21]
Hi. When I use Aeolus plugin as vst3 instrument in daw(reaper), the reverb and output volume go up max immediately at some points. It happens at the start and the end of playback for sure, but occasionally in the middle of playback. I can't figure out the exact condition of this event. But it happens repeatedly.

I am using intel i7-9700, 24gb ram pc and windows 11. I tested it with another midi file on other daws like Cakewalk by Bandlab, Tracktion Waveform. I could find out it happens on them too. 

I recorded a quick demonstration here.
https://www.youtube.com/watch?v=h2EGvRaniVc

**Comment by Archie3d** [comment]
Hi, thanks for the video, it helps a lot to understand the issue :)
The plugin responds to the MIDI control commands (like program change `PC`, volume `CC7` or effect `CC91`), and it looks like your MIDI file sets CC7 Volume to max at the beginning of the track (this is very common for MIDI files). You can check this in Reaper and remove these CC commands in each track:
![image](https://user-images.githubusercontent.com/5774953/227728022-43af559a-3705-4478-b628-5d698089078d.png)

Mind that the CCs can also be present throughout the MIDI file so you will need to clean them up as well.

**Comment by sangiye0** [comment]
Thank you. It was just like you said. CC7 Volume MSB was 100. Also CC91 Effects Level was 127 and it was repeated in the whole file. Now I can lower the value as I want. I don't know why I didn't notice it before when I played with piano instrument or other synthesizers. Anyway, the problem is solved. Thank you for your help.
