### ISSUE TITLE
More organ stops

### ISSUE THREAD

**Issue by rsp4jack** [Archie3d/aeolus_plugin#23]

**Comment by lewisalexander2020** [comment]
Could you elaborate on this please?. what do you want regarding stops and are you looking at a 2, 3 or 4 manual spec? I'm new to this particular area, but a serving organist / developer and having had the hell of dealing with aeolus in linux which I care to forget lol, this software can use some expansion I agree, but what do you want from it?

**Comment by Archie3d** [comment]
For more stops you can either reuse the original Aeolus `*.ae0` files, or create custom pipe models. If you have any particular ideas of the stops you'd like to see, let me know.

**Comment by lewisalexander2020** [comment]
are there any available libraries or can the latest stops for 0.10.4 of aeolus be used? what would I need to do to get that working with this app?

sorry for the daft questions,

lew :)

**Comment by Archie3d** [comment]
Hi, I've just checked on aeolus-0.10.4, and thought the engine has been updated, I don't see the updated stops. The stops seem to be the same (https://kokkinizita.linuxaudio.org/linuxaudio/downloads/stops-0.4.0.tar.bz2) so I already have them in my build.
