### ISSUE TITLE
Update JUCE to the latest version (7.0.9 at the moment)

### ISSUE THREAD

**Issue by trolley813** [Archie3d/aeolus_plugin#28]
Aeolus uses JUCE 7.0.5, which had the bug (juce-framework/JUCE#1242, fixed in 7.0.6 AFAIK) when the _Audio/MIDI Settings_ window does not show up on Linux with GNOME (and maybe some other DEs), and it's impossible to change the settings e.g. MIDI inputs. The only way to change them was to re-login from other DE session which does not have this behaviour (e.g. Cinnamon).

I've tested with 7.0.9 (building from source), all seems to work fine (Arch Linux/EndeavourOS with GNOME 45).

The reason for this being an issue rather than a pull request is that the change is tiny (one only has to update the submodule to the latest tag).

**Comment by lewisalexander2020** [comment]
I support this request also.

lew

**Comment by trolley813** [comment]
Great! Thanks
