### ISSUE TITLE
Allow multiple key-switches to be assigned in the config

### ISSUE THREAD

**Issue by Archie3d** [Archie3d/aeolus_plugin#29]
Current configuration allows only one MIDI key to be assigned to sequencer action;:
```json
  "sequencer": {
      "backward_key": 22,
      "forward_key": 23
  }
```

Extend this to allow multiple keys:

```json
  "sequencer": {
      "backward_key": [22, 36],
      "forward_key": [23, 37]
  }
```

**Comment by Archie3d** [comment]
@Synthematophon This now should be in the [develop](https://github.com/Archie3d/aeolus_plugin/tree/develop) branch.

**Comment by Synthematophon** [comment]
> @Synthematophon This now should be in the [develop](https://github.com/Archie3d/aeolus_plugin/tree/develop) branch.

  "sequencer": {
      "backward_key": [22, 36],
      "forward_key": [23, 37]
  }
where are these steps to be defined? In the default_organ.json file?

**Comment by Archie3d** [comment]
Yes, either in [default_organ.json](https://github.com/Archie3d/aeolus_plugin/blob/46745cabcd231acf39ab31f561b449a4c6bd5fde/Resources/configs/default_organ.json#L204) (look at the bottom) if you use a built-in configuration, or in `Documents/Aeolus/organ_config.json` if you use an external config file.

**Comment by Synthematophon** [comment]
Thanks!

 
 

Gesendet: Montag, 10. Juni 2024 um 10:58 Uhr
Von: "Arthur Benilov" ***@***.***>
An: "Archie3d/aeolus_plugin" ***@***.***>
Cc: "Synthematophon" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [Archie3d/aeolus_plugin] Allow multiple key-switches to be assigned in the config (Issue #29)


 

Yes, either in default_organ.json (look at the bottom) if you use a built-in configuration, or in Documents/Aeolus/organ_config.json if you use an external config file.
