### ISSUE TITLE
Feature request: Changeable A4 pitch and temperament

### ISSUE THREAD

**Issue by Gnusmas49** [Archie3d/aeolus_plugin#3]
Organ music in different regions and time periods was (is) usually played with different pitch standards and temperaments.  It would be nice to make them tweakable in the plugin.  By the way, thank you very much for this amazing project!

**Comment by Archie3d** [comment]
Hi, thank you for the feedback. Yes, adjustable tuning in on my to do list, I'll make sure it's in the next version.
