### ISSUE TITLE
.clap format release

### ISSUE THREAD

**Issue by RustoMCSpit** [Archie3d/aeolus_plugin#31]

**Comment by Archie3d** [comment]
JUCE does not support clap natively (yet). What would be a benefit of adding clap support?

**Comment by RustoMCSpit** [comment]
> JUCE does not support clap natively (yet). What would be a benefit of adding clap support?

i want to add this to my list https://github.com/RustoMCSpit/awesome-linux-clap-list

juce has a clap addon btw

**Comment by CodesoundR** [comment]
... follow

**Comment by RustoMCSpit** [comment]
> ... follow

?

**Comment by CodesoundR** [comment]
> > ... follow
> 
> ?

I follow this request. I hope to see this tool on linux in the .clap format
cheers

**Comment by Archie3d** [comment]
Ok, I've added the clap wrapper, you may check the build artefacts here:
[Windows](https://github.com/Archie3d/aeolus_plugin/actions/runs/10442699661/artifacts/1824986233)
[macOS](https://github.com/Archie3d/aeolus_plugin/actions/runs/10442699661/artifacts/1824986231)
[Linux](https://github.com/Archie3d/aeolus_plugin/actions/runs/10442699661/artifacts/1824986230)

I've only tried Windows build with Reaper, seems to work. If it's all fine to you I will add this to the next release.

**Comment by RustoMCSpit** [comment]
please edit the readme, also thanks!

**Comment by CodesoundR** [comment]
I wanted to thank you for bringing this exceptional pipe organ to the .clap format!
greetings
