### ISSUE TITLE
Couplers issues

### ISSUE THREAD

**Issue by Synthematophon** [Archie3d/aeolus_plugin#34]
I noticed a few more things about the couplers (you call it "link" in the code):

1. on a real organ, a note that has already sounded cannot be played again on a coupled manual. This is because the corresponding pipe can only sound once (at the same time).
If I then release the key again, the tone stops completely although the original tone (the original key) is still pressed.
2. a coupled tone (e.g. I. manual linked to the pedal) sounds louder in the pedal than in the original. 
3. if, for example, manual II is coupled to manual I and additionally manual I to the pedal, the 2nd manual also sounds with the pedal tone, although only the first manual is coupled to the pedal. This is not the normal behavior of a real organ.

**Comment by Archie3d** [comment]
I am not sure I understand. The coupling implementation works "upwards", for example when manual 1 is coupled to manual 2 whatever you play on manual 1 will be translated to manual 2, but whatever you play on manual 2 will not be translated to manual 1 (this is what I mean by the "upwards" coupling). I will need to check my referenced about this.

**Comment by Synthematophon** [comment]
In principle, that is probably correct, even if I understand it the other way around:
If, for example, I couple manual I to the pedal, then I play the notes of the coupled manual with the pedal keys. The same applies to the other manuals. I don't know which other organs you are familiar with: it is not always the case that manual I is the Great. However, the Choir division can also be located here (especially with English organs). In German (baroque) organs, this can also be the so-called Rückpositiv. If the Great is then on the second manual, I is of course coupled to II. The swell is often on the 3rd manual. Here it is simple: Swell to Great means: if you play on manual II, the III. manual also sounds.

No matter how you look at it, as coupling upwards or downwards, it also works with your organ model. Only the double sounding of an already coupled pipe does not exist in "nature".

Translated with www.DeepL.com/Translator (free version)



 

Gesendet: Freitag, 26. Juli 2024 um 00:38 Uhr
Von: "Arthur Benilov" ***@***.***>
An: "Archie3d/aeolus_plugin" ***@***.***>
Cc: "Synthematophon" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Archie3d/aeolus_plugin] Couplers issues (Issue #34)


 

I am not sure I understand. The coupling implementation works "upwards", for example when manual 1 is coupled to manual 2 whatever you play on manual 1 will be translated to manual 2, but whatever you play on manual 2 will not be translated to manual 1 (this is what I mean by the "upwards" coupling). I will need to check my referenced about this.

**Comment by Archie3d** [comment]
Oh, yeah, you are right, this is a regression. It is not supposed to trigger the same pipes twice.

**Comment by Archie3d** [comment]
This should be fixed now.
