### ISSUE TITLE
Reverb module has crackling issues at low latencies (e.g. 64 Samples ASIO-Buffer)

### ISSUE THREAD

**Issue by Seljo1** [Archie3d/aeolus_plugin#39]
While the organ alone plays well at low latencies (64 ASIO samples), as soon as I move the reverb slider away from 0 position, there appears cracklingg in the sound output. If I pull the reverb fader to 0, then the sound is nice and uncrackled. I need to add an external reverb plugin afer the organ to avoid the internal reverb and thus to be able to play at low latencies.
Tested with v 0.2.0 and 0.2.1, same.
Tested as plugin and as standalone with ASIO, both the same at 64 sample buffer size, both crackling.

**Comment by Archie3d** [comment]
Does this happen for you when using "Elveden Hall" reverb IR (this is the only non zero-delay one)?

**Comment by Seljo1** [comment]
Just tested Elveden Hall and the same crackling, when the reverb slider is higher than 0.
Just tested appending ReaVerb from Reaper just for testing another convolution reverb, and that does not crackle, but hasn't the nice church tails of Aeolus.

**Comment by Archie3d** [comment]
I see, thanks for trying.
Do you mind telling me your system specs? Also, what is your audio interface (is it a proper ASIO or smth like ASIO4ALL ?), and the sampling rate?
I can run 64 samples frame on my laptop (MBP M1), will test on Windows machine later, so could be the performance struggle of my reverb implementation. Though, I must say 64 samples frame is quite a stretch, real organs have much worse responsiveness.
Meanwhile, if you are fine with Reaper's convolver you can grab the IRs from here: https://github.com/Archie3d/aeolus_plugin/tree/master/Resources/irs

**Comment by Seljo1** [comment]
Well the specs are: i5 12500H Win11
RME Babyface (very first old version, but ASIO drivers from RME are up to date), works well at 64 Samples at 44.100 Hz with most synths. CPU load is not high, but only unevenly distributed over time, so some buffers get missed on a regular basis.
The provided IRs I'll try as soon as I get home, didn't know they are there. Thanks a lot for these, and the organ itself especially!

**Comment by Seljo1** [comment]
Tested the IRs in ReVerb, and it sounds verry similar, or even identical, like in Aeolus. If FFT-size is set too low, then also ReaVerb crackles, which is unintuitive, I thought long FFT is mor CPU intensitive, but what do I know... :-)
The sound is really fantastic, very competitive to real organ manufacturers (mid sized PA system needed, though, hihi)

**Comment by Archie3d** [comment]
The plugin uses non-uniform partitioning convolution with the max FFT size of 8192 samples. Just tested it on i9-9900K (which should be slower than your i5-10500H), and I had no problem running it with 64 samples frame in Reaper, so I am not sure where the bottleneck is. Well, at least you can use the IRs separately.
BTW, if you have a 5.1 or 7.1 system you may try a multichannel version of the plugin.

**Comment by Seljo1** [comment]
Yes, multichannel sounds tempting, but I'm still stereo-only equipped. And I'm not sure, if headphone-surround-simulation is actually valid.
But I liked the York Minster IR the most, but didn't like the long pre-delay in the IR, so I deleted the first silent part completely, so now it is more to my liking, even if it is acoustically untrue in a real church due to distances, I like the immediate response more. I attached the artifact, if you want to test the changed behaviour.
[york_minster_no-delay.zip](https://github.com/user-attachments/files/17173670/york_minster_no-delay.zip)

**Comment by Archie3d** [comment]
Hi, I actually do multichannel surround to stereo mapping inside the plugin already, so yeah, that's about how it would sound in headphones.
The delay in IRs is left on purpose actually. The reverb slider in the plugin only controls the wet part of the reverb, the dry direct sound is always there at nominal gain, so you always get the immediate sound plus a slightly delayed reverb. This should normally favour the perspective of a player sitting the closest to the pipes. Removing the delay from the IR will get you a more reverberant sound, as from the perspective of someone sitting in the hall (so the direct and reverberant sounds reach them more or less simultaneously, or the direct even being obstructed). I suppose, it's the matter of preference, but removing the delay can actually be useful for performance reasons, since this allows skipping the zero-delay portion of the reverb (which is very CPU hungry), which will make the convolution faster but will introduce the delay back. But since it's been removed from the IR they should compensate. So in the future I may consider removing the 4096 samples from the IRs and switch the convolver to non-zero delay mode.

**Comment by Seljo1** [comment]
Ah, now I understand, why I prefer the audience experience, which is without pre-delay, - because I always sit in the audience and not in the player's bench! :-)
To re-purpose the computational delay as the reverb pre-delay and save CPU cycles that way, is a clever idea, and a good plan to implement - because my Laptop behaves like an organ blower due to the heavy work, haha.

**Comment by elpeh** [comment]
> [...] So in the future I may consider removing the 4096 samples from the IRs and switch the convolver to non-zero delay mode.

Could you make that configurable?

**Comment by Archie3d** [comment]
> Could you make that configurable?

Sure, but I hope the audible difference will be negligible with the IRs provided (they all have a delay at the beginning), so zero-delay part of the convolution can be disabled altogether.

**Comment by Archie3d** [comment]
Implemented in `develop` branch. IRs offets have been adjusted, zero-delay part disabled for better performance.

**Comment by Archie3d** [comment]
I had to revert this change since non-zero delay reverb does not sound to me.
