### ISSUE TITLE
MIDI NoteON vs actives stop 

### ISSUE THREAD

**Issue by dewal5** [Archie3d/aeolus_plugin#4]
Please consider modify  follow issue:

In all I know pipe organ VST (Hauptwerk, Organteq, Grand Orgue etc) when you change stop of organ (e.g Flute) then it take effect on allredy sended MIDI.sendNote. Thus 

For now in this stage of this app change of stops acts diffrent. 

When you change stop there is no change in sound until you add new notesOn by MIDI

**Comment by Archie3d** [comment]
Available in [v0.1.12](https://github.com/Archie3d/aeolus_plugin/releases/tag/v0.1.12)

**Comment by dewal5** [comment]
My man!  Works flawless :)  ________  M.   
            
          
     
      
       
        Dnia 9 listopada 2021 21:38 Arthur Benilov ***@***.***&gt; napisał(a):
       
    
       
         
 Available in  github.com v0.1.12
