### ISSUE TITLE
Multiple plugins of this cause stuttering

### ISSUE THREAD

**Issue by muziker** [Archie3d/aeolus_plugin#8]
Using v0.1.12-20-gla0d0f0, it seems like having two of these in a raper project causes Reaper's time line updates to start stuttering

**Comment by Archie3d** [comment]
Hi, could you elaborate on this? What do you mean by timeline stuttering?
I constantly use multiple instances on Reaper on Windows and do not experience this.
What is your OS? What plugin format do you use? Do you observe high CPU load?

**Comment by Archie3d** [comment]
Cannot reproduce this, and there is too little info provided.
